const pageContent = {
  about: {
    title: 'What we do',
    content: `
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam. Nec dui nunc mattis enim ut tellus. Velit scelerisque in dictum non consectetur a erat nam. Augue eget arcu dictum varius duis at. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Auctor urna nunc id cursus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sit amet tellus cras adipiscing. Volutpat est velit egestas dui id ornare arcu odio ut. Nibh tellus molestie nunc non. Leo in vitae turpis massa sed elementum tempus egestas sed. At lectus urna duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare.</p>
    <p>Odio ut sem nulla pharetra diam sit. Massa placerat duis ultricies lacus sed turpis tincidunt. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Gravida arcu ac tortor dignissim convallis aenean et tortor. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ultricies lacus sed turpis tincidunt id aliquet risus. Pellentesque id nibh tortor id aliquet lectus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Ultricies mi eget mauris pharetra et ultrices. Dolor morbi non arcu risus quis varius quam quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Aliquam etiam erat velit scelerisque in dictum.</p>
    <p>Nec ultrices dui sapien eget. Sit amet volutpat consequat mauris nunc. Orci nulla pellentesque dignissim enim sit amet. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Mauris nunc congue nisi vitae suscipit. Vitae auctor eu augue ut. Scelerisque purus semper eget duis at. Habitant morbi tristique senectus et. Elit pellentesque habitant morbi tristique.</p>
    <p>Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed vulputate odio ut. Felis eget velit aliquet sagittis id. Vulputate ut pharetra sit amet aliquam. Blandit turpis cursus in hac habitasse. Bibendum enim facilisis gravida neque convallis. In iaculis nunc sed augue lacus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Sit amet purus gravida quis.</p>
    `
  },
  'digital-divide': {
    title: 'The digital divide',
    content: `
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam. Nec dui nunc mattis enim ut tellus. Velit scelerisque in dictum non consectetur a erat nam. Augue eget arcu dictum varius duis at. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Auctor urna nunc id cursus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sit amet tellus cras adipiscing. Volutpat est velit egestas dui id ornare arcu odio ut. Nibh tellus molestie nunc non. Leo in vitae turpis massa sed elementum tempus egestas sed. At lectus urna duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare.</p>
    <p>Odio ut sem nulla pharetra diam sit. Massa placerat duis ultricies lacus sed turpis tincidunt. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Gravida arcu ac tortor dignissim convallis aenean et tortor. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ultricies lacus sed turpis tincidunt id aliquet risus. Pellentesque id nibh tortor id aliquet lectus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Ultricies mi eget mauris pharetra et ultrices. Dolor morbi non arcu risus quis varius quam quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Aliquam etiam erat velit scelerisque in dictum.</p>
    <p>Nec ultrices dui sapien eget. Sit amet volutpat consequat mauris nunc. Orci nulla pellentesque dignissim enim sit amet. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Mauris nunc congue nisi vitae suscipit. Vitae auctor eu augue ut. Scelerisque purus semper eget duis at. Habitant morbi tristique senectus et. Elit pellentesque habitant morbi tristique.</p>
    <p>Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed vulputate odio ut. Felis eget velit aliquet sagittis id. Vulputate ut pharetra sit amet aliquam. Blandit turpis cursus in hac habitasse. Bibendum enim facilisis gravida neque convallis. In iaculis nunc sed augue lacus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Sit amet purus gravida quis.</p>
    `
  },
  'get-involved': {
    title: 'Get involved',
    content: `
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam. Nec dui nunc mattis enim ut tellus. Velit scelerisque in dictum non consectetur a erat nam. Augue eget arcu dictum varius duis at. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Auctor urna nunc id cursus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sit amet tellus cras adipiscing. Volutpat est velit egestas dui id ornare arcu odio ut. Nibh tellus molestie nunc non. Leo in vitae turpis massa sed elementum tempus egestas sed. At lectus urna duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare.</p>
    <p>Odio ut sem nulla pharetra diam sit. Massa placerat duis ultricies lacus sed turpis tincidunt. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Gravida arcu ac tortor dignissim convallis aenean et tortor. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ultricies lacus sed turpis tincidunt id aliquet risus. Pellentesque id nibh tortor id aliquet lectus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Ultricies mi eget mauris pharetra et ultrices. Dolor morbi non arcu risus quis varius quam quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Aliquam etiam erat velit scelerisque in dictum.</p>
    <p>Nec ultrices dui sapien eget. Sit amet volutpat consequat mauris nunc. Orci nulla pellentesque dignissim enim sit amet. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Mauris nunc congue nisi vitae suscipit. Vitae auctor eu augue ut. Scelerisque purus semper eget duis at. Habitant morbi tristique senectus et. Elit pellentesque habitant morbi tristique.</p>
    <p>Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed vulputate odio ut. Felis eget velit aliquet sagittis id. Vulputate ut pharetra sit amet aliquam. Blandit turpis cursus in hac habitasse. Bibendum enim facilisis gravida neque convallis. In iaculis nunc sed augue lacus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Sit amet purus gravida quis.</p>
    `
  },
  'our-network': {
    title: 'Who we work with',
    content: `
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam. Nec dui nunc mattis enim ut tellus. Velit scelerisque in dictum non consectetur a erat nam. Augue eget arcu dictum varius duis at. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Auctor urna nunc id cursus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sit amet tellus cras adipiscing. Volutpat est velit egestas dui id ornare arcu odio ut. Nibh tellus molestie nunc non. Leo in vitae turpis massa sed elementum tempus egestas sed. At lectus urna duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare.</p>
    <p>Odio ut sem nulla pharetra diam sit. Massa placerat duis ultricies lacus sed turpis tincidunt. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Gravida arcu ac tortor dignissim convallis aenean et tortor. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ultricies lacus sed turpis tincidunt id aliquet risus. Pellentesque id nibh tortor id aliquet lectus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Ultricies mi eget mauris pharetra et ultrices. Dolor morbi non arcu risus quis varius quam quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Aliquam etiam erat velit scelerisque in dictum.</p>
    <p>Nec ultrices dui sapien eget. Sit amet volutpat consequat mauris nunc. Orci nulla pellentesque dignissim enim sit amet. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Mauris nunc congue nisi vitae suscipit. Vitae auctor eu augue ut. Scelerisque purus semper eget duis at. Habitant morbi tristique senectus et. Elit pellentesque habitant morbi tristique.</p>
    <p>Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed vulputate odio ut. Felis eget velit aliquet sagittis id. Vulputate ut pharetra sit amet aliquam. Blandit turpis cursus in hac habitasse. Bibendum enim facilisis gravida neque convallis. In iaculis nunc sed augue lacus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Sit amet purus gravida quis.</p>
    `
  },
  'insights': {
    title: 'Predicting the future',
    content: `
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam. Nec dui nunc mattis enim ut tellus. Velit scelerisque in dictum non consectetur a erat nam. Augue eget arcu dictum varius duis at. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Auctor urna nunc id cursus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sit amet tellus cras adipiscing. Volutpat est velit egestas dui id ornare arcu odio ut. Nibh tellus molestie nunc non. Leo in vitae turpis massa sed elementum tempus egestas sed. At lectus urna duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare.</p>
    <p>Odio ut sem nulla pharetra diam sit. Massa placerat duis ultricies lacus sed turpis tincidunt. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Gravida arcu ac tortor dignissim convallis aenean et tortor. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ultricies lacus sed turpis tincidunt id aliquet risus. Pellentesque id nibh tortor id aliquet lectus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Ultricies mi eget mauris pharetra et ultrices. Dolor morbi non arcu risus quis varius quam quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Aliquam etiam erat velit scelerisque in dictum.</p>
    <p>Nec ultrices dui sapien eget. Sit amet volutpat consequat mauris nunc. Orci nulla pellentesque dignissim enim sit amet. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Mauris nunc congue nisi vitae suscipit. Vitae auctor eu augue ut. Scelerisque purus semper eget duis at. Habitant morbi tristique senectus et. Elit pellentesque habitant morbi tristique.</p>
    <p>Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed vulputate odio ut. Felis eget velit aliquet sagittis id. Vulputate ut pharetra sit amet aliquam. Blandit turpis cursus in hac habitasse. Bibendum enim facilisis gravida neque convallis. In iaculis nunc sed augue lacus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Sit amet purus gravida quis.</p>
    `
  },
};

const getPageContent = (pageId = 'about') => pageContent[pageId];

export default getPageContent;